#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scalac-scoverage-plugin
Version  : 1.3.1
Release  : 1
URL      : https://github.com/scoverage/scalac-scoverage-plugin/archive/v1.3.1.tar.gz
Source0  : https://github.com/scoverage/scalac-scoverage-plugin/archive/v1.3.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1/scalac-scoverage-plugin_2.12-1.3.1.jar
Source2  : https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1/scalac-scoverage-plugin_2.12-1.3.1.pom
Source3  : https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1/scalac-scoverage-runtime_2.12-1.3.1.jar
Source4  : https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1/scalac-scoverage-runtime_2.12-1.3.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-scalac-scoverage-plugin-data = %{version}-%{release}
Requires: mvn-scalac-scoverage-plugin-license = %{version}-%{release}

%description
scalac-scoverage-plugin
==========
scoverage is a free Apache licensed code coverage tool for scala that offers statement and branch coverage.
scoverage is available for sbt, maven, and gradle.

%package data
Summary: data components for the mvn-scalac-scoverage-plugin package.
Group: Data

%description data
data components for the mvn-scalac-scoverage-plugin package.


%package license
Summary: license components for the mvn-scalac-scoverage-plugin package.
Group: Default

%description license
license components for the mvn-scalac-scoverage-plugin package.


%prep
%setup -q -n scalac-scoverage-plugin-1.3.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-scalac-scoverage-plugin
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-scalac-scoverage-plugin/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1/scalac-scoverage-plugin_2.12-1.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1/scalac-scoverage-plugin_2.12-1.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1/scalac-scoverage-runtime_2.12-1.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1/scalac-scoverage-runtime_2.12-1.3.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1/scalac-scoverage-plugin_2.12-1.3.1.jar
/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-plugin_2.12/1.3.1/scalac-scoverage-plugin_2.12-1.3.1.pom
/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1/scalac-scoverage-runtime_2.12-1.3.1.jar
/usr/share/java/.m2/repository/org/scoverage/scalac-scoverage-runtime_2.12/1.3.1/scalac-scoverage-runtime_2.12-1.3.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-scalac-scoverage-plugin/LICENSE
